name: Deploy Flask App to AWS EC2

on:
  push:
    branches:
      - main
      - staging
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest --junitxml=test-results.xml

  deploy-staging:
    needs: build
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2 and Deploy to Staging
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST_STAGING }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY_STAGING }}
          script: |
            cd ${{ secrets.EC2_PATH }}
            git pull origin staging
            pip install -r requirements.txt
            pkill -f app.py || true
            nohup python3 app.py > app.log 2>&1 &

  deploy-production:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 and Deploy to production
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST_PROD }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY_PROD }}
          script: |
            cd ${{ secrets.EC2_PATH }}
            git pull origin main
            pip install -r requirements.txt
            pkill -f app.py || true
            nohup python3 app.py > app.log 2>&1 &
